# Variables
EXE=reversi

# Special rules and targets
.PHONY: all build clean help

# Rules and targets
all: build

build:
	@cd src && $(MAKE)
	@cp -f src/$(EXE) ./

clean:
	@cd src && $(MAKE) clean
	@rm -f $(EXE)

help:
	@echo "Usage:"
	@echo " make all\t\tRuns the whole build of reversi"
	@echo " make reversi\t\tBuilds the executable file from reversi.c"
	@echo " make clean\t\tRemove all files generated by make"
	@echo " make help\t\tDisplay this help"
